services:
  - type: web
    name: clinicplus-api
    runtime: go
    branch: main
    buildCommand: go build -o main ./cmd/server
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clinicplus
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: GOOSE_DRIVER
        value: postgres
      - key: GOOSE_DBSTRING
        fromDatabase:
          name: clinicplus
          property: connectionString
      - key: GOOSE_MIGRATIONS_DIR
        value: migrations 

databases:
  - name: clinicplus
    plan: free
    region: oregon