services:
  - type: web
    name: clinicplus-api
    runtime: go
    branch: main
    buildCommand: go mod download && go build -o main
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clinicplus
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: clinicplus
    plan: free
    region: oregon