services:
  - type: web
    name: clinicplus-api
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clinicplus
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: clinicplus
    plan: free
    region: oregon